const navBarList = [
    {
        title:'便攜式喇叭',
        text:'簡易攜帶，音質絕美，隨身享受音樂的沉浸感',
        content:[{
            name:'MARSHELL',
            bg:'008-1.jpg'
        },{
            name:'LOVE',
            bg:'008-2.jpg'
        },{
            name:'RONY',
            bg:'008-3.jpg'
        },{
            name:'Edifier',
            bg:'034.jpg'
        },{
            name:'FOCAL',
            bg:'035.jpg'
        },{
            name:'B&O',
            bg:'036.jpg'
        }]
    },{
        title:'書架喇叭',
        text:'美型外觀，融入居家生活',
        content:[{
            name:'Dali',
            bg:'031.jpg'
        },{
            name:'KLIPSCH',
            bg:'031-1.jpg'
        },{
            name:'KEF',
            bg:'031-2.jpg'
        },{
            name:'B&W',
            bg:'034.jpg'
        },{
            name:'WHARFEDALE',
            bg:'035.jpg'
        },{
            name:'ATC',
            bg:'036.jpg'
        }]
    },{
        title:'重低音',
        text:'',
        content:[{
            name:'YAMAHA',
            bg:'028.jpg'
        },{
            name:'MAGNAT',
            bg:'028-1.jpg'
        },{
            name:'AUDIOLAB',
            bg:'028-2.jpg'
        },{
            name:'MARANTZ',
            bg:'034.jpg'
        },{
            name:'ACCUPHASE',
            bg:'035.jpg'
        },{
            name:'HEGEL',
            bg:'036.jpg'
        }]
    },{
        title:'落地喇叭',
        text:'呼天撼地，讓人陶醉在每分每秒的澎湃樂章',
        content:[{
            name:'Dali',
            bg:'025.jpg'
        },{
            name:'KLIPSCH',
            bg:'026.jpg'
        },{
            name:'KEF',
            bg:'027.jpg'
        },{
            name:'B&W',
            bg:'034.jpg'
        },{
            name:'WHARFEDALE',
            bg:'035.jpg'
        },{
            name:'ATC',
            bg:'036.jpg'
        }]
    }, 
];

export { navBarList };