const navBarList = [
    {
        title:'便攜式喇叭',
        content:[{
            name:'MARSHELL',
            bg:'028.jpg'
        },{
            name:'LOVE',
            bg:'029.jpg'
        },{
            name:'RONY',
            bg:'030.jpg'
        },{
            name:'Edifier',
            bg:'034.jpg'
        },{
            name:'FOCAL',
            bg:'035.jpg'
        },{
            name:'B&O',
            bg:'036.jpg'
        }]
    },{
        title:'書架喇叭',
        content:[{
            name:'Dali',
            bg:'032.jpg'
        },{
            name:'KLIPSCH',
            bg:'038.jpg'
        },{
            name:'KEF',
            bg:'039.jpg'
        },{
            name:'B&W',
            bg:'034.jpg'
        },{
            name:'WHARFEDALE',
            bg:'035.jpg'
        },{
            name:'ATC',
            bg:'036.jpg'
        }]
    },{
        title:'擴大機',
        content:[{
            name:'YAMAHA',
            bg:'028.jpg'
        },{
            name:'MAGNAT',
            bg:'029.jpg'
        },{
            name:'AUDIOLAB',
            bg:'030.jpg'
        },{
            name:'MARANTZ',
            bg:'034.jpg'
        },{
            name:'ACCUPHASE',
            bg:'035.jpg'
        },{
            name:'HEGEL',
            bg:'036.jpg'
        }]
    },{
        title:'落地喇叭',
        content:[{
            name:'Dali',
            bg:'028.jpg'
        },{
            name:'KLIPSCH',
            bg:'029.jpg'
        },{
            name:'KEF',
            bg:'030.jpg'
        },{
            name:'B&W',
            bg:'034.jpg'
        },{
            name:'WHARFEDALE',
            bg:'035.jpg'
        },{
            name:'ATC',
            bg:'036.jpg'
        }]
    }, 
];

export { navBarList };